### ISSUE TITLE
Krita & AI Script installed But when Ai generation is Activated it shows an Error

### ISSUE THREAD

**Issue by bokipeki** [Acly/krita-ai-diffusion#167] opened 2023-12-01 15:02 UTC
Krita & AI Script installed But when Ai generation is Activated it shows an Error.

I will include screen shots of what it looks like.

I used: krita_ai_diffusion-1.8.2 script
I installed the newest Krita version for Mac.

The error reads:
Server Execution error: convolution_overridable nor implemented. You are likely triggering this with tension backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function.

This is how everything looks. Any advice on what is happening?

![Screenshot 2023-12-01 at 9 00 45 AM](https://github.com/Acly/krita-ai-diffusion/assets/152630328/93c6c513-ee1f-41c2-b4f6-03d607cf0e3e)

![Screenshot 2023-12-01 at 9 00 17 AM](https://github.com/Acly/krita-ai-diffusion/assets/152630328/179bad82-e11e-45bf-a57e-50f47c29cd76)

![Screenshot 2023-12-01 at 9 00 04 AM](https://github.com/Acly/krita-ai-diffusion/assets/152630328/cb8efaf5-a6c9-4430-8700-528b7cd9760d)

**Comment by Acly** [comment] 2023-12-01 17:24
Duplicate of #157

Need someone with apple hardware to experiment a bit and figure this one out I think...

**Comment by Acly** [comment] 2023-12-10 17:27
I saw some Mac/MPS related commits in [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) repo. Maybe it fixes the issue?
Version [1.10.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.10.0) of the plugin will also update ComfyUI_IPAdapter_plus to a newer version.

**Comment by DavidLMS** [comment] 2024-01-18 23:26
I am having the same problem. Using the version 1.12.0 of the plugin. Both on M1 and M3 Pro.

**Comment by bokipeki** [comment] 2024-01-28 14:21
> I think the problem is the canvas size. Try with a 512x512.

Wow! I did it and it worked! Thank you for such an easy solution!

**Closed** 2024-01-28 14:21 UTC
Labels: mac-os
