### ISSUE TITLE
A suggest for dev ,input comfyui json to custom workflow.

### ISSUE THREAD

**Issue by se7enth** [Acly/krita-ai-diffusion#295] opened 2024-01-02 18:34 UTC
here is a idea for more  comfy.  
why not set the configure setting for load a full comfyui workflow. Of course, these workflows must follow certain specifications, e.g. upscale operations can only be performed in the upscaler of the krita plugin, and the inputs must correspond to the layers and be set up (for this functionality we can set up special nodes in the comfyui to connect to mark the input nodes inside the comfyui). in this mode ,we dont need configure model, lora in Krita  because it setting in comfyui.
I believe that by managing the inputs and outputs, we can do anything image related with krita and comfyui!

**Comment by Acly** [comment] 2024-01-03 10:48
Duplicate of #153, please discuss there

**Closed by Acly** 2024-01-03 10:48 UTC
