### ISSUE TITLE
Prompt field breaks with two-windows setup [reproduction included]

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#123] opened 2023-11-25 15:18 UTC
To reproduce this behavior:

1 - create/open project
2 - Window > New Window (it will create a copy of the interface
3 - Window > New View > Select your project (it will duplicate in live mode your window with project now)
4 - try to type in any prompt into text field

You'll quickly discover that you keep triggering some hotkeys instead typing. Because the text field doesn't keep focus from all opened windows and second window triggers regular hotkeys.
This setup specifically good if you have a monitor + cintiq and draw on fully-opened canvas on cintiq while having overall picture with tools on your monitor. Super handy, but the bug kills the experience :/

[restarting Krita helped and solved. Dunno what was that, but will be a good idea to double-check this thing]

**Comment by Acly** [comment] 2023-11-25 20:26
I couldn't reproduce that particular issue, but multiple windows with views on the same document are problematic for the docker. Krita also always insits to create the docker on both windows, and even if you close it on one it's still kind of there.

Proper support requires a bit of rework, which I had planned anyway, but not sure how soon. I've been running a setup similar to yours, but just moved the AI-generation docker to a second monitor, rather than create a new Krita window. It's not exactly the same of course, but... safe.

**Closed** 2023-11-28 03:05 UTC
