### ISSUE TITLE
could not find lora lightning and others, can't use 1.17 at all error on all samplers, plus missing samplers.

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#640] opened 2024-04-21 02:32 UTC
I'm having to roll back and reinstall, on every style preset i get this error.
I am not using a lora just prompt"cat to test.
i noticed all the normal samplers are gone, and "edit custom preset" yellow writing does nothing.
charging samplers trying all options i still get this error. 
its like there are no samplers

ValueError: Could not find LoRA 'lightning' used by sampler preset 'Realtime Lightning'
2024-04-21 10:22:59,811 ERROR Error: Could not find LoRA 'lightning' used by sampler preset 'Realtime Lightning'
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 147, in generate
    input = workflow.prepare(
  File "C:\Users\pc\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 804, in prepare
    i.models.loras += _get_sampling_lora(style, is_live, model_set, models)
  File "C:\Users\pc\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 982, in _get_sampling_lora
    raise ValueError(
ValueError: Could not find LoRA 'lightning' used by sampler preset 'Realtime Lightning'

**Comment by rbfbatx** [comment] 2024-04-21 03:33
I am also having this issue. The Lightning LORA does not appear in the drop down filter at all.

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 04:03
> I am also having this issue. The Lightning LORA does not appear in the drop down filter at all.

I tried all the new ones and all error, 
also can't work out how to make custom as Acly mentioned ie DPM++ 3M Karas that recommended for lightning models,
i noticed the Lighting one he has is Euler. very odd.
I wish there was a normal selection list and custom list rather than the new list 
but its very broken, so I'm back on 1.15 as 1.16 has some bugs. hopefully 1.17.1 is out and fixes it plus a way to get DPM++ 2M Karas back etc

**Comment by freecoderwaifu** [comment] 2024-04-21 05:47
Temp fix:

Make sure you have `sdxl_lightning_8step_lora.safetensors` in your `ComfyUI\models\loras\` folder, either in your local server which should be inside `AppData\Roaming\krita\pykrita\ai_diffusion` or your custom server path.

You can download that Lora from here:
https://huggingface.co/ByteDance/SDXL-Lightning/blob/main/sdxl_lightning_8step_lora.safetensors

Open `AppData\Roaming\krita\pykrita\ai_diffusion\resources.py` in Notepad or better yet Notepad++
https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/resources.py

Search  `resource_id(ResourceKind.lora, SDVersion.sdxl, "lightning"): ["sdxl_lightning_8step_lora"],` (line 766) and just add `.safetensors `at the end of `sdxl_lightning_8step_lora`. It should look like this:

`resource_id(ResourceKind.lora, SDVersion.sdxl, "lightning"): ["sdxl_lightning_8step_lora.safetensors"],`

Save and relaunch and it should work. Notice it's for SDXL models only. 

If you want the old "Lightning" selection that worked with SD 1.5, which I think was just sgm_uniform used as a scheduler, then you could make a custom preset like this:

```
 {
    "Old Lightning (sgm_uniform)": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "sgm_uniform",
        "steps": 12,
        "cfg": 7.0
    }
}
```

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 06:52
> "Edit custom presets" and it should open up samplers.json

thanks, 
the "Edit custom presets" does not work clicking nothing opens, samplers.json is not in my dir, i searched both app data krita and C: to try and find it but nothing, 
i found C:\Users\px\AppData\Roaming\krita\ai_diffusion\presets
that matches the example edited and does nothing, so duplicate renamed to DPM++ 2M karas 
}
 {
    "DPM++ 2M karas ": {
        "sampler": "dpmpp_2m_sde_gpu",
        "scheduler": "karras",
        "steps": 10,
        "cfg": 3.0
    }
but does nothing. 
currently at a loss, its no just lightning that errors, its all, few SD1.5 work on custom from my preset everything else i get error

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 07:08
ps
for when it is working would would these be right?

 {
    "DPM++ 3M - GPU": {
        "sampler": "dpmpp_3m_sd_gpu",
        "scheduler": "sgm_uniform",
        "steps": 30
        "cfg": 7.0
    }
}
 {
    "DPM++ 3M Karras": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "karras",
        "steps": 40,
        "cfg": 7.0
    }
}
 {
    "Euler": {
        "sampler": "euler",
        "scheduler": "exponential",
        "steps": 20,
        "cfg": 7.0
    }
}

and can you do say,
 {
    "Euler": {
        "sampler": "euler",
        "scheduler": "sgm_uniform",
        "steps": 20,
        "cfg": 7.0
    }
}
I have no clue on these clearly trying to work it out i'm finding no videos to explain, im use to a1111

**Comment by Acly** [comment] 2024-04-21 07:15
I tried deleting my lightning lora, and cannot reproduce it. All the samplers work fine, except for "Realtime (Lightning)" (which is expected, it's the only one which uses the lora).

My theory is that there was a mismatch for your existing styles, if they previously had the "Lightning" option selected (or maybe Euler) they were matched to the "Realtime (Lightning)" mode? But it should be fine when you choose any other preset!

> i noticed the Lighting one he has is Euler. very odd.

Lightning uses Euler, see https://huggingface.co/ByteDance/SDXL-Lightning#comfyui-usage
This is not a change, same as before.

>  plus a way to get DPM++ 2M Karas back etc

That's the Default preset, also no change there. I can put the names back for people who are used to them.

> If you want the old "Lightning" selection that worked with SD 1.5, which I think was just sgm_uniform used as a scheduler,

Very confused by this. Old "Lightning" is identical to "Realtime (Lightning)". None of the old options ever used DPM++ 3M.

> Search resource_id(ResourceKind.lora, SDVersion.sdxl, "lightning"): ["sdxl_lightning_8step_lora"], (line 766) and just add .safetensors at the end of sdxl_lightning_8step_lora

Should work without the modification (a partial match is fine, extension not needed). Was that an issue?

> i noticed all the normal samplers are gone, and "edit custom preset" yellow writing does nothing.

See #634, I will fix that

> https://comfy.icu/node/Sampler-Selector
> https://comfy.icu/node/Scheduler-Selector

Yep those are the options, I will try to add them as comment to the preset file maybe

**Comment by Acly** [comment] 2024-04-21 07:21
Also for reference:
* the built-in options are in `<appdata>/krita/pykrita/ai_diffusion/presets/samplers.json` and look like [this](https://github.com/Acly/krita-ai-diffusion/blob/v1.17.0/ai_diffusion/presets/samplers.json)
* the user options are in `<appdata>/krita/ai_diffusion/presets/samplers.json` and follow the same scheme

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 07:36
> Also for reference:
> 
>     * the built-in options are in `<appdata>/krita/pykrita/ai_diffusion/presets/samplers.json` and look like [this](https://github.com/Acly/krita-ai-diffusion/blob/v1.17.0/ai_diffusion/presets/samplers.json)
> 
>     * the user options are in `<appdata>/krita/ai_diffusion/presets/samplers.json` and follow the same scheme

thanks re installing again 3rd times a charm. will let you know what happens

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 07:52
> Also for reference:
> 
>     * the built-in options are in `<appdata>/krita/pykrita/ai_diffusion/presets/samplers.json` and look like [this](https://github.com/Acly/krita-ai-diffusion/blob/v1.17.0/ai_diffusion/presets/samplers.json)
> 
>     * the user options are in `<appdata>/krita/ai_diffusion/presets/samplers.json` and follow the same scheme

    raise ValueError(
ValueError: The LoRA '' used by style 'SDXL - Colorful v1.7' is not available on the server

its a no go, no SDXLs work doesn't mater what sampler is selected just get error, 

also C:\Users\pc\AppData\Roaming\krita\ai_diffusion\presets
samplers.json
edited but its not showing in drop down selection was hoping to test, 
what i put in, but looks like that dir or file are not being read.
```
 {
    "DPM++ 3M": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "exponential",
        "steps": 30,
        "cfg": 7.0
    }
    "Old Lightning (sgm_uniform)": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "sgm_uniform",
        "steps": 12,
        "cfg": 7.0
    }
    "DPM++ 3M SDE": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "sgm_uniform",
        "steps": 30
        "cfg": 7.0
    }
    "DPM++ 2M SDE - GPU": {
        "sampler": "dpmpp_2m_sde_gpu",
        "scheduler": "karras",
        "steps": 20,
        "cfg": 7.0
    }
    "Euler Ancestral": {
        "sampler": "euler_ancestral",
        "scheduler": "exponential",
        "steps": 20,
        "cfg": 7.0
    }
}
```

**Comment by Acly** [comment] 2024-04-21 07:57
I think it's missing some commas between the presets. Can you check client.log? It should have error messages if there is something wrong with the file.

> ValueError: The LoRA '' used by style 'SDXL - Colorful v1.7' is not available on the server

This sounds more like an issue with the Lora setup for that style.

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 08:13
> I think it's missing some commas between the presets. Can you check client.log? It should have error messages if there is something wrong with the file.
> 
> > ValueError: The LoRA '' used by style 'SDXL - Colorful v1.7' is not available on the server
> 
> This sounds more like an issue with the Lora setup for that style.

testing, there was a black lora deleted blank as was causing the issue no colorful model,
odd its working, 
other than the custom  C:\Users\pc\AppData\Roaming\krita\ai_diffusion\presets
samplers.json

i noticed yours in C:\Users\pc\AppData\Roaming\krita\pykrita\ai_diffusion\presets
had , so tried that but that file is certainly not been read at this time.
 
```
{
    "DPM++ 3M": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "exponential",
        "steps": 30,
        "cfg": 7.0
    },
    "Old Lightning (sgm_uniform)": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "sgm_uniform",
        "steps": 12,
        "cfg": 7.0
    },
    "DPM++ 3M SDE": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "sgm_uniform",
        "steps": 30
        "cfg": 7.0
    },
    "DPM++ 2M SDE - GPU": {
        "sampler": "dpmpp_2m_sde_gpu",
        "scheduler": "karras",
        "steps": 20,
        "cfg": 7.0
    },
    "Euler Ancestral": {
        "sampler": "euler_ancestral",
        "scheduler": "exponential",
        "steps": 20,
        "cfg": 7.0
    }
}
```
so possibly a install update glitch no idea, plus the blank empty lora spot, that use to be ignored on 1.14 if it was blank so use to leave then for fast setting up.

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 08:17
ps names on samplers as DPM++ etc make more sense since civitAi models have listed there setting where i see lightning with DPM++ 3m karras, thats why confused no eula, 
i personally think the old naming makes more sense when adding new models as faster to work out.

**Comment by rbfbatx** [comment] 2024-04-21 15:26
I was able to fix it by just creating a  folder structure in the server location. I created a SDXL folder and sd1. 5 folder and then put the Loras where they are suppose to be and it all started working right.

**Comment by Acly** [comment] 2024-04-21 15:38
In the end I'm not quite sure why the "Edit custom presets" link doesn't work yet, I tried to delete my file association but it kinda worked anyway (Windows asked me which program to open with). Maybe it's related to windows version...

Anyway, added Euler A preset and the sampler names to the preset title.
https://github.com/Acly/krita-ai-diffusion/wiki/Samplers

**Comment by freecoderwaifu** [comment] 2024-04-21 17:10
> > If you want the old "Lightning" selection that worked with SD 1.5, which I think was just sgm_uniform used as a scheduler,
> 
> Very confused by this. Old "Lightning" is identical to "Realtime (Lightning)". None of the old options ever used DPM++ 3M.
> 
> > Search resource_id(ResourceKind.lora, SDVersion.sdxl, "lightning"): ["sdxl_lightning_8step_lora"], (line 766) and just add .safetensors at the end of sdxl_lightning_8step_lora
> 
> Should work without the modification (a partial match is fine, extension not needed). Was that an issue?
> 
@Acly 

Oh using DPM++ 3M was just an example for setting sgm_uniform as the scheduler, I guess it was using Euler + SGM all along. I also ran into this issue originally because I use the Lightning option all the time for Live mode with my models before 1.17, since it retains shading better, while LCM tends to give thick edges and flat colors. Even if the Lightning Lora didn't apply for 1.5 before (and maybe it was just working by chance for me lol), the Lightning option still gives me good results due to the sampler and scheduler combo at lower steps.

You are right though, the Lightning Lora code is right and partial matches work fine. I must have messed up my testing between moving the Lora to its folder and trying again. It does understandably throw a Lora not found error for 1.5, which is what must have thrown me off initially. One thing I noticed though is the red error messages tend to stick even after resolving their issue. 

Also I couldn't find a way for custom styles to refresh without a full restart of the server and Krita, a refresh button next to it would be welcome.

**Comment by rbfbatx** [comment] 2024-04-21 17:22
Would someone post the edit I need to make in the .json file to add the "Old Lightning" scheduler/scheduler back to the options? I am confused as to what was previously being used. 

    },
    "Old Lightning (*****)": {
        "sampler": "*****",
        "scheduler": "*****",
        "steps": 12,
        "cfg": 7.0
    },

**Comment by freecoderwaifu** [comment] 2024-04-21 17:39
```
{
    "Lightning without Lora": {
        "sampler": "euler",
        "scheduler": "sgm_uniform",
        "steps": 12,
        "cfg": 7.0
    }
}

```
You can set your own steps and cfg, you can also edit them with the sliders anyway.

The old Lightning and the current Lightning are the same, as in both are Euler SGM Uniform. the difference is setting it as a preset won't force the use of the Lightning Lora, since it's understandable that Lora only works for SDXL now.

**Comment by rbfbatx** [comment] 2024-04-21 17:57
> @freecoderwaifu
> 
> Thank you. The sdxl_lightning_8step_lora has again disappeared from my settings. I opened Krita and it re-downloaded the LCM lora, I suppose because I moved them to subfolders. Other than that and the edits I made in the preset .json folder, nothing changed so I am unsure what caused the issue to repeat.
> 
> I am back to getting the lora not available in server error.


Nevermind, I went into my folders, moved the lora out of the folder it was in and it appeared in the settings again. No idea what is going on there.

**Comment by rbfbatx** [comment] 2024-04-21 18:18
> > @freecoderwaifu
> > Thank you. The sdxl_lightning_8step_lora has again disappeared from my settings. I opened Krita and it re-downloaded the LCM lora, I suppose because I moved them to subfolders. Other than that and the edits I made in the preset .json folder, nothing changed so I am unsure what caused the issue to repeat.
> > I am back to getting the lora not available in server error.
> 
> Nevermind, I went into my folders, moved the lora out of the folder it was in and it appeared in the settings again. No idea what is going on there.

Okay... so this is happening anytime that krita is restarted. I have to go into the loras folder for the custom server and move the file. Once the file has been moved and I refresh in settings the problem is resolved.

**Comment by Acly** [comment] 2024-04-21 18:37
@rbfbatx I don't really understand what you are trying to do anymore :)

For Lightning merges (full SDXL checkpoint that already has a bit of Lightning merged in) you don't use the Lora at all. You just select the Turbo/Lightning sampler option (that's DPM++ SDE Karras, which most of these work with) and you're good.

If you want to Lightning-ify any regular SDXL checkpoint, you download the 8-step lightning lora and put it into your lora folder. Then you select the "Realtime Lightning" sampler. *It will add the Lora automatically.* Don't add it in the style's Lora settings. It shouldn't even appear there.

If you just want the sampler settings of the previous "Lightning" sampler, but without using the Lora, use the preset as posted by @freecoderwaifu (same settings, no auto-lora).

I am only guessing the confusion is that the lightning lora is now treated specially and it wasn't before? The idea behind having sampler presets add the lora automatically is that you can use LCM/Lightning with their Lora just for Live mode.

**Comment by rbfbatx** [comment] 2024-04-21 19:49
>  If you want to Lightning-ify any regular SDXL checkpoint, you download the 8-step lightning lora and put it into your lora folder. Then you select the "Realtime Lightning" sampler. It will add the Lora automatically. Don't add it in the style's Lora settings. It shouldn't even appear there.

Yes, that would be the issue. That would be the same issue that I think several people are having. I don't think that it was made clear in your release notes that it would be functioning entirely different from other loras, particularly given that it had not functioned like that previously.

**Comment by Acly** [comment] 2024-04-21 20:23
Fair enough, maybe a warning if you added it manually on top of the sampler would be a better system.

**Comment by Sil3ntKn1ght** [comment] 2024-04-21 23:52
> In the end I'm not quite sure why the "Edit custom presets" link doesn't work yet, I tried to delete my file association but it kinda worked anyway (Windows asked me which program to open with). Maybe it's related to windows version...
> 
> Anyway, added Euler A preset and the sampler names to the preset title. https://github.com/Acly/krita-ai-diffusion/wiki/Samplers

im on Windows 10, i did try editing the main one with your in it and adding but when i started krita there where no samplers.

on the auto fill for <lora: 
only working if you do have a enter new paragraph ie

`detail, photo, cat <lora: this will work `
but
```
detail, photo, cat 

<lora: this will not work work
```

i like having the break makes it easier to find and edit on long prompts.

i do agree render are different testing prompts, but it might be ComfyUI update somewhere on the AI i thought

**Comment by Sil3ntKn1ght** [comment] 2024-04-22 00:01
> > > If you want the old "Lightning" selection that worked with SD 1.5, which I think was just sgm_uniform used as a scheduler,
> > 
> > 
> > Very confused by this. Old "Lightning" is identical to "Realtime (Lightning)". None of the old options ever used DPM++ 3M.
> > > Search resource_id(ResourceKind.lora, SDVersion.sdxl, "lightning"): ["sdxl_lightning_8step_lora"], (line 766) and just add .safetensors at the end of sdxl_lightning_8step_lora
> > 
> > 
> > Should work without the modification (a partial match is fine, extension not needed). Was that an issue?
> 
> @Acly
> 
> Oh using DPM++ 3M was just an example for setting sgm_uniform as the scheduler, I guess it was using Euler + SGM all along. I also ran into this issue originally because I use the Lightning option all the time for Live mode with my models before 1.17, since it retains shading better, while LCM tends to give thick edges and flat colors. Even if the Lightning Lora didn't apply for 1.5 before (and maybe it was just working by chance for me lol), the Lightning option still gives me good results due to the sampler and scheduler combo at lower steps.
> 
> You are right though, the Lightning Lora code is right and partial matches work fine. I must have messed up my testing between moving the Lora to its folder and trying again. It does understandably throw a Lora not found error for 1.5, which is what must have thrown me off initially. One thing I noticed though is the red error messages tend to stick even after resolving their issue.
> 
> Also I couldn't find a way for custom presets to refresh without a full restart of the server and Krita, a refresh button next to the new custom presets dropdown would be welcome.

i think that might have happened to me on the first 2 installs of 1.17 might have been a moved model or something and the error message stayed but i exited and reloaded so many time and all samplers and models did it, somehow 3rd or 4th install it resolved. 
but thinking about it one model had a blank lora 

**Acly Sir** is it possible the error was on all models due to that one model having the blank lora?
since after removing that, everything started working.

**Comment by Sil3ntKn1ght** [comment] 2024-04-22 09:22
definitely some odd this, so i decided to put 1.15 and 1.17 on my system, the lighting of 1.15 is beautiful, but same settings same prompt 1.17 Lighting well all except Eula are a mess. I have no idea why.
from the looks despite what they say i feel all but Eula are not linking maybe to what they should and are defaulting ignoring the setting. I say that because 1.15 all work differently speeds looks etc, but 1.17 every sampler the results look the same and are a mess same speeds etc etc. but for Eula sampler that one does looking different.
I'm at a loss to why this is.

iv been using both on this system and there definitely something strange in 1.17

**Comment by Sil3ntKn1ght** [comment] 2024-04-23 08:12
got samplers working if like
"karras" (custom 1): {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "exponential",
        "steps": 20,
        "cfg": 7.0
it won't read, and conflicts and doesn't read if there matching name

bellow worked. i have no idea what the stuff means I'm mixing testing and working out.
i get good results with these.

{
    "DPM++ 3M": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "exponential",
        "steps": 20,
        "cfg": 7.0
    },
    "DPM++ 3m karras": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "karras",
        "steps": 30,
        "cfg": 4.0
    },
    "DPM++ 3M SDE Lightning": {
        "sampler": "dpmpp_3m_sde",
        "scheduler": "sgm_uniform",
        "steps": 8,
        "cfg": 2.0
    },
    "DPM++ 2M SDE karras GPU": {
        "sampler": "dpmpp_2m_sde_gpu",
        "scheduler": "karras",
        "steps": 20,
        "cfg": 5
    },
    "DPM++ 2M SDE karras": {
        "sampler": "dpmpp_2m_sde",
        "scheduler": "karras",
        "steps": 20,
        "cfg": 5
    },
    "Euler": {
        "sampler": "euler",
        "scheduler": "sgm_uniform",
        "steps": 20,
        "cfg": 6.0
    },
    "Euler Ex": {
        "sampler": "euler",
        "scheduler": "exponential",
        "steps": 10,
        "cfg": 2.0
    },
    "Lightning Euler": {
        "sampler": "euler",
        "scheduler": "sgm_uniform",
        "lora": "lightning",
        "steps": 10,
        "cfg": 1.5
    },
    "Lightning Euler DDI": {
        "sampler": "euler",
        "scheduler": "ddim_uniform",
        "lora": "lightning",
        "steps": 8,
        "cfg": 1.5
    },
    "Euler DDI": {
        "sampler": "euler",
        "scheduler": "ddim_uniform",
        "steps": 14,
        "cfg": 3.0
    }
}

**Comment by freecoderwaifu** [comment] 2024-04-23 16:12
> got samplers working if like "karras" (custom 1): { "sampler": "dpmpp_3m_sde", "scheduler": "exponential", "steps": 20, "cfg": 7.0 it won't read, and conflicts and doesn't read if there matching name

Name should be in between `""` like this: 

{
"karras (custom 1)": {
"sampler": "dpmpp_3m_sde",
"scheduler": "exponential",
"steps": 20,
"cfg": 7.0
},

**Comment by Sil3ntKn1ght** [comment] 2024-04-25 08:38
> Temp fix:
> 
> Make sure you have `sdxl_lightning_8step_lora.safetensors` in your `ComfyUI\models\loras\` folder, either in your local server which should be inside `AppData\Roaming\krita\pykrita\ai_diffusion` or your custom server path.
> 
> You can download that Lora from here: https://huggingface.co/ByteDance/SDXL-Lightning/blob/main/sdxl_lightning_8step_lora.safetensors
> 
> Open `AppData\Roaming\krita\pykrita\ai_diffusion\resources.py` in Notepad or better yet Notepad++ https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/resources.py
> 
> Search `resource_id(ResourceKind.lora, SDVersion.sdxl, "lightning"): ["sdxl_lightning_8step_lora"],` (line 766) and just add `.safetensors `at the end of `sdxl_lightning_8step_lora`. It should look like this:
> 
> `resource_id(ResourceKind.lora, SDVersion.sdxl, "lightning"): ["sdxl_lightning_8step_lora.safetensors"],`
> 
> Save and relaunch and it should work. Notice it's for SDXL models only.
> 
> If you want the old "Lightning" selection that worked with SD 1.5, which I think was just sgm_uniform used as a scheduler, then you could make a custom preset like this (click on where it says "Edit custom presets" and it should open up samplers.json in Notepad):
> 
> ```
>  {
>     "Old Lightning (sgm_uniform)": {
>         "sampler": "dpmpp_3m_sde",
>         "scheduler": "sgm_uniform",
>         "steps": 12,
>         "cfg": 7.0
>     }
> }
> ```
> 
> You can edit "sampler" and "scheduler" to get back the older ones, just combine sampler "dpmpp_3m_sde_gpu" (or non gpu) with scheduler "karras" to get "DPM++ 3M Karras". Here's the best list I could find in a quick 5 second google search for what you should type as their names.
> 
> https://comfy.icu/node/Sampler-Selector https://comfy.icu/node/Scheduler-Selector
> 
> To add multiple custom entries, just copy the above code example and paste it multiple times like this:
> 
> ```
>  {
>     "Custom 1": {
>         "sampler": "dpmpp_3m_sde",
>         "scheduler": "sgm_uniform",
>         "steps": 30
>         "cfg": 7.0
>     }
> }
>  {
>     "Custom 2": {
>         "sampler": "dpmpp_2m_sde_gpu",
>         "scheduler": "karras",
>         "steps": 40,
>         "cfg": 7.0
>     }
> }
>  {
>     "Custom 3": {
>         "sampler": "euler_ancestral",
>         "scheduler": "exponential",
>         "steps": 20,
>         "cfg": 7.0
>     }
> }
> ```

yep default samplers error needed to download this and put in lora dir
sdxl_lightning_8step_lora.safetensors

**Comment by Sil3ntKn1ght** [comment] 2024-04-25 10:18
I'll make a video and post link tomorrow, 

Sampler in 1.17 are very broken. after trying to make the missing samplers and even the default samplers in 1.17 there are so many artifices.

older versions no issue 1.17 is definitely broken.

easier to do a video to show. so will do that tomorrow, i originally thought it was me but after testing now on 2 systems both lora missing using lighting sampler and both artifacts on renders only Eula sampler works correctly

**Comment by Acly** [comment] 2024-04-25 10:50
Maybe it will be clearer. I'm really not sure what you are testing.

The built-in presets use exactly the same settings as previous version and produce the same images. They just have a different name.

The Realtime/Lightning preset requires the Lora. If you don't have it you get an error. That's expected.

Custom presets you simply get what you ask for. Not all combinations work are produce good images, most don't.

**Comment by Sil3ntKn1ght** [comment] 2024-04-26 04:46
> Maybe it will be clearer. I'm really not sure what you are testing.
> 
> The built-in presets use exactly the same settings as previous version and produce the same images. They just have a different name.
> 
> The Realtime/Lightning preset requires the Lora. If you don't have it you get an error. That's expected.
> 
> Custom presets you simply get what you ask for. Not all combinations work are produce good images, most don't.

this is the best way i can show the samplers default one not working as they should, my autism and dyslexic spelling and just trying to convey the issue is hard so i did the video to show it.  

https://youtu.be/Ngt5Oqa7aqE?si=U79_ZQ3dP7itE6YN

**Closed** 2024-04-26 12:19 UTC

**Comment by Acly** [comment] 2024-04-27 12:30
[1.17.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.1) addresses most issues mentioned here. It won't magically make things work as before, but hopefully give some more options and fix or clear up the issues.
