### ISSUE TITLE
[ discussion ] Storing history in *.kra file

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#232] opened 2023-12-13 22:29 UTC
So, the title.
Is it possible to write extra meta in *.kra file, native to Krita projects, with the generation history, specifically prompts. At least prompts.
Or the process of the file composing is hard-coded and cannot be modified with an addon? 
If so, is it possible to store it as external file/subfolder with all related stuff, which on the file opening will be retrieved, in case it exists.

**Comment by daniel-richter** [comment] 2023-12-15 12:23
If you click "Apply" and add a result as a new layer, the name of the layer should contain the prompt (at least that's how it is in the version I have installed). With that, the prompts will be saved to the *.kra file.

**Comment by Pirog17000** [comment] 2023-12-15 16:51
I do that too, the point is to store prompts AND be able to safely rename the layers into something more readable

**Comment by Acly** [comment] 2023-12-15 17:19
Duplicate of #110

**Comment by Acly** [comment] 2023-12-15 17:20
.kra files are just ZIP archives as far as I know.
There is also a `imageSaved` event from Krita when a document is written.
So I gather it should be possible to add the plugin's state to the file.

But I haven't tested any of this yet, it will be some work.

**Comment by Muskelmagier** [comment] 2023-12-16 07:48
Maybe something similar like Buli notes
https://krita-artists.org/t/buli-notes/20504

I use this as a stopgap to store my prompt and seed in the .kra file

**Comment by Acly** [comment] 2023-12-17 10:47
It seems to use "annotation" feature instead of manipualting .kra files directly, probably a good idea if it works for arbitrary large data.

**Comment by Acly** [comment] 2024-01-05 22:15
Done in [1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0)

**Closed by Acly** 2024-01-05 22:15 UTC
Labels: enhancement
